unstable_features = true
comment_width = 120
condense_wildcard_suffixes = true
combine_control_expr = false
enum_discrim_align_threshold = 40
fn_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "One"
inline_attribute_width = 60
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
struct_field_align_threshold = 40
hard_tabs = true
trailing_comma = "Always"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
force_explicit_abi = true
style_edition = "2024"
